// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("WebApplication1.Models.GameLevel", b =>
                {
                    b.Property<int>("levelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("LevelId");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("levelId");

                    b.ToTable("GameLevels");

                    b.HasData(
                        new
                        {
                            levelId = 1,
                            Description = "Basic questions",
                            Title = "Easy"
                        },
                        new
                        {
                            levelId = 2,
                            Description = "Intermediate questions",
                            Title = "Medium"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.GameResult", b =>
                {
                    b.Property<int>("resultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("QuizzResultId");

                    b.Property<DateTime>("CompletionDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("CompletionDate");

                    b.Property<int>("LevelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LevelId");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UserId");

                    b.HasKey("resultId");

                    b.HasIndex("LevelId");

                    b.HasIndex("UserId");

                    b.ToTable("GameResults");

                    b.HasData(
                        new
                        {
                            resultId = 1,
                            CompletionDate = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LevelId = 1,
                            Score = 100,
                            UserId = 1
                        },
                        new
                        {
                            resultId = 2,
                            CompletionDate = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LevelId = 2,
                            Score = 85,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Question", b =>
                {
                    b.Property<int>("questionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("QuestionId");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentQuestion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LevelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LevelId");

                    b.Property<string>("Option1")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Option2")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Option3")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Option4")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("questionId");

                    b.HasIndex("LevelId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            questionId = 1,
                            Answer = "4",
                            ContentQuestion = "What is 2 + 2?",
                            LevelId = 1,
                            Option1 = "3",
                            Option2 = "4",
                            Option3 = "5",
                            Option4 = "22"
                        },
                        new
                        {
                            questionId = 2,
                            Answer = "Mars",
                            ContentQuestion = "Which planet is known as the Red Planet?",
                            LevelId = 1,
                            Option1 = "Earth",
                            Option2 = "Mars",
                            Option3 = "Jupiter",
                            Option4 = "Venus"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Region", b =>
                {
                    b.Property<int>("regionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("RegionId");

                    b.Property<string>("regionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("regionId");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            regionId = 1,
                            regionName = "Africa"
                        },
                        new
                        {
                            regionId = 2,
                            regionName = "Asia"
                        },
                        new
                        {
                            regionId = 3,
                            regionName = "Europe"
                        },
                        new
                        {
                            regionId = 4,
                            regionName = "North America"
                        },
                        new
                        {
                            regionId = 5,
                            regionName = "South America"
                        },
                        new
                        {
                            regionId = 6,
                            regionName = "Oceania"
                        },
                        new
                        {
                            regionId = 7,
                            regionName = "Antarctica"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Role", b =>
                {
                    b.Property<int>("roleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("RoleId");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("roleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            roleId = 1,
                            Name = "Cleric"
                        },
                        new
                        {
                            roleId = 2,
                            Name = "Warrior"
                        },
                        new
                        {
                            roleId = 3,
                            Name = "Knight"
                        },
                        new
                        {
                            roleId = 4,
                            Name = "Mage"
                        },
                        new
                        {
                            roleId = 5,
                            Name = "Ranger"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LinkAvatar")
                        .HasColumnType("TEXT");

                    b.Property<string>("OTP")
                        .HasColumnType("TEXT")
                        .HasColumnName("OTP");

                    b.Property<int?>("RegionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RegionId");

                    b.Property<int?>("RoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RoleId");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("RegionId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "john@example.com",
                            IsDeleted = false,
                            LinkAvatar = "avt1.png",
                            OTP = "123456",
                            RegionId = 1,
                            RoleId = 2,
                            UserName = "john_doe"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "jane@example.com",
                            IsDeleted = false,
                            LinkAvatar = "avt2.png",
                            OTP = "654321",
                            RegionId = 2,
                            RoleId = 2,
                            UserName = "jane_smith"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.GameResult", b =>
                {
                    b.HasOne("WebApplication1.Models.GameLevel", "Level")
                        .WithMany("GameResults")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.User", "User")
                        .WithMany("GameResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication1.Models.Question", b =>
                {
                    b.HasOne("WebApplication1.Models.GameLevel", "Level")
                        .WithMany("Questions")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.HasOne("WebApplication1.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebApplication1.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Region");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WebApplication1.Models.GameLevel", b =>
                {
                    b.Navigation("GameResults");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.Navigation("GameResults");
                });
#pragma warning restore 612, 618
        }
    }
}
